ModLanguage("*", {
	"REPLACE ALL": {
            "Cursor": "Knife",
        },
	"Cursor": "Knife",
	"Cursor (short)": "Knife",
	"Grandma (short)": "Cooker",
	"Grandma": "Cooker",
	"Farm": "spaghetti",
	"Farm (short)": "spaghetti",
	"Mine": "Fries",
	"Mine (short)": "Fries",
	"Factory": "Cake",
	"Factory (short)": "Cake",
	"Bank": "Hamburger",
	"Bank (short)": "Hamburger",
	"Temple": "Steak",
	"Temple (short)": "Steak",
	"Wizard tower": "Coca cola",
	"Wizard tower (short)": "Coca cola",
	"Shipment": "Slushy",
	"Shipment (short)": "Slushy",
	"Alchemy lab": "Sandwich",
	"Alchemy lab (short)": "Sandwich",
	"Portal": "Chicken",
	"Portal (short)": "Chicken",
	"Time machine": "Kinder egg",
	"Time machine (short)": "Kinder egg",
	"Antimatter condenser": "Pizza",
	"Antimatter condenser (short)": "Pizza",
	"Prism": "Popcorn",
	"Prism (short)": "Popcorn",
	"Chancemaker": "Jelly",
	"Chancemaker (short)": "Jelly",
	"Fractal engine": "Hot dog",
	"Fractal engine (short)": "Hot dog",
	"Javascript console": "Candy strip",
	"Javascript console (short)": "Candy strip",
	"Idleverse": "Donut",
	"Idleverse (short)": "Donut",
	"Cortex baker": "chips",
	"Cortex baker (short)": "Chips",
})